### ISSUE TITLE
Cursor is seen through Fullscreen photo using standard smooch Messaging Component

### ISSUE THREAD

**Issue by gemmakbarlow** [zendesk/sunshine-conversations-ios#105]
Hi Smooch Team,

One of our testers just raised this issue which appears to be an issue with the standard messaging component. 

Here's our Podfile entry

```
  pod 'Smooch', '4.2.2'           # Previously SupportKit.
  pod 'SmoochHelpKit', '1.1.0'    # Previously SupportKit.
```

and we're running an iOS project with a 9.0 deployment target, compiled against iOS 9.3. I've included a screenshot of myself reproducing the issue below. 

---

FREQUENCY
Every Time

ACTION
1. Upload a photo via the Smooch 'messages' component 
2. Send any text message
3. Tap and hold the text to highlight it
4. Tap the photo you've uploaded

EXPECTED RESULT
The blue highlight cursor should disappear once the photo is opened full screen

ACTUAL RESULT
The blue cursor displays over the photo when the photo is opened full screen

ADDITIONAL INFORMATION
iPhone 6 iOS 9.3.2 WiFi
Reproducible 3/3

**Comment by gemmakbarlow** [comment]
![note blue dot](https://cloud.githubusercontent.com/assets/337963/16715581/ff191a10-46b1-11e6-980a-1f731a3f0363.PNG)

**Comment by gemmakbarlow** [comment]
![note - blue dot](https://cloud.githubusercontent.com/assets/337963/16715584/1c99bce8-46b2-11e6-860e-a18eef985ee4.PNG)

**Comment by DataWearsAHood** [comment]
Hi Gemma,

I'm doing some housekeeping cleaning up old issue reports; Are you still running into this with the latest SDK release (v9.0.0)?

**Comment by gemmakbarlow** [comment]
> Hi Gemma,
> 
> I'm doing some housekeeping cleaning up old issue reports; Are you still running into this with the latest SDK release (v9.0.0)?

Thanks for checking in @DataWearsAHood. We can close this, I've moved on from this employer.
