### ISSUE TITLE
Localization for customizing of base text isn't suitable.

### ISSUE THREAD

**Issue by williamsjj** [zendesk/sunshine-conversations-ios#17]
Using Localization as the mechanism to customize UI text isn't really suitable. For example:

"Messages" = "Chat"

Is what we have to do to customize the Message button to say "Chat". However, if we upload this to our translation tool, all the French/German/Arabic/etc translators will see is "Messages" as the text to translate, when what we want is a translation of the word Chat. 

It's even worse when you consider the conversation text:

"This is the start of your conversation with the %@ team. We'll stay in touch to help you get the most out of your app.\nFeel free to leave us a message about anything that’s on your mind. We’ll get back to your questions, suggestions or anything else as soon as we can." 

Customizing the various text really need to be configurable via SKTSettings, rather than a hack using localization.

**Comment by qadirsuh** [comment]
@mspensieri Any update regarding this enhancement.

**Comment by warpling** [comment]
Would love to see this as well! Still using the localization hack.
