### ISSUE TITLE
Ability to pull screenshot on demand

### ISSUE THREAD

**Issue by williamsjj** [zendesk/sunshine-conversations-ios#19]
It would be REALLY helpful if we could request a screenshot from a customer during a help chat. It's really frustrating to the customer to try describe what they're looking at sometimes and we're losing folks in that process. Optimally it would work something like:

1.) We would include text like [request_screenshot] in our reply.
2.) When the user is in the Conversation screen, that text would put SupportKit into "screenshot" mode which would tell the user  to go to the screen they wish to share and shake the phone to transmit the screenshot.
3.) Show the conversation window after the screenshot has been taken and show an upload progress.
4.) Screenshot should be attached to an email and sent just like a chat.

**Comment by DataWearsAHood** [comment]
Hi Jason,

Due to when this was first opened, the product team has asked if this is still relevant for you, as well as which Sunshine Conversations customer your are working on behalf of.
