### ISSUE TITLE
CocoaLumberjack support to allow attaching logs to a support chat.

### ISSUE THREAD

**Issue by williamsjj** [zendesk/sunshine-conversations-ios#20]
It would be very helpful to be able to make SupportKit a log target in CocoaLumberjack...like https://github.com/TechSmith/CrashlyticsLumberjack does for Crashlytics. That way when a user starts/continues a chat, the logs are uploaded to SupportKit and a link to them is inserted into the support messages sent to us (it would be really awesome if the link took us to the SupportKit portal where there was a log interface with searching). It would allow us to see exactly what's going on behind the scenes of the app to help our users more quickly and effectively.

**Comment by DataWearsAHood** [comment]
Hi Jason,

Due to when this was first opened, the product team has asked if this is still relevant for you, as well as which Sunshine Conversations customer your are working on behalf of.
