### ISSUE TITLE
Can't add attachments, plus icon not working

### ISSUE THREAD

**Issue by gregorpichler** [zendesk/sunshine-conversations-ios#204]
**What is the current behavior?**
Users can't click on the plus icon to add attachments. Tapping the plus icon does nothing. No alert sheet is coming up.

![IMG_0F8D5B5831A9-1](https://user-images.githubusercontent.com/4091405/66555427-f3b1c100-eb4e-11e9-8cb3-9f784b265f87.jpeg)

That's how we setup Smooch:

```
let settings = SKTSettings(appId: "xxxxxxx")
settings.conversationAccentColor = Color.accent.uiColor
settings.allowedMenuItems = [SKTMenuItemCamera, SKTMenuItemGallery]

Smooch.initWith(settings)
Smooch.addSmoochProperties()
Smooch.showConversation(from: vc)
```

Also the keys `NSCameraUsageDescription, NSPhotoLibraryUsageDescription, NSPhotoLibraryAddUsageDescription` are present in the Info.plist file.

 **What is the expected behavior?**
Alert sheet that shows options to select either camera or gallery.

 **Please tell us about your environment:**
- SDK version 7.1.1
- OS version 13.1.2

**Comment by mspensieri** [comment]
Thanks for the report, I've filed this internally for someone on our team to take a look at. We'll update here with progress or additional questions.

**Comment by gregorpichler** [comment]
Quick update, could confirm that the plus button is working on the iPad. 

![IMG_5B010D700F50-1](https://user-images.githubusercontent.com/4091405/66914096-5820c480-f016-11e9-99a8-e117cbc47f39.jpeg)

**Comment by gregorpichler** [comment]
Still not working with Smooch 8.0.0

The weird thing is that the alert sheet comes up on the simulator but not on a real device (iPhone 11).

**Comment by DataWearsAHood** [comment]
Hi Gregor,

The dev team looked this over and was not able to reproduce the issue, both on a physical device and an iPhoneX simulator (internal-ref: SCO-323).
If you continue to experience this issue with v9.0.0 and the /demo app, feel free to let us know.

**Comment by quimoune** [comment]
Hi guys, I've got exactly the same issue as @gregorpichler.. :(
With Smooch (9.0.0), integrated as childViewController.
I try with storyboard & xib with using the window.
I package a sample code.
[NewTabBar.zip](https://github.com/zendesk/sunshine-conversations-ios/files/5526755/NewTabBar.zip)
Thanks..
