### ISSUE TITLE
Smooch SDK is using deprecated UIWebView

### ISSUE THREAD

**Issue by baltameme** [zendesk/sunshine-conversations-ios#206]
**What is the current behavior?**
While trying to submit my app to the App Store I receive the warning  message below after finalizing processing the uploaded build:

_Dear Developer,

We identified one or more issues with a recent delivery for your app, "App Name" 1.0 (107). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information._

* From my side, all my project's source code is completely using WKWebView. However, i followed this [article](https://stackoverflow.com/questions/58442629/itms-90809-deprecated-api-usage-apple-will-stop-accepting-submissions-of-apps) to check if there is any dependencies that is using UIWebView and found that Smooch is one of them on my project, and shows the warning on this line:

Binary file ./Pods/Smooch/Smooch.framework.dSYM/Contents/Resources/DWARF/Smooch matches

My Question is how can I resolve this issue and avoid this warning from your side?

**Comment by wmora** [comment]
Hello! We don't use `UIWebView` anywhere in the SDK so not sure why the framework is being flagged for it. I'll file it internally for the team to discuss.

**Comment by DataWearsAHood** [comment]
Hello!

The team confirmed the details below:

> It is the Smooch.framework.dSYM file that contains a reference to UIWebView, which is an additional file that is distributed as part of the release, so [your] crash reports are symbolicated with the Smooch SDK symbols.
> The main artefact Smooch.framework that is distributed which is the SDK, does not contain any references to UIWebView when a grep is performed.
> App’s submitted to the AppStore with just the Smooch.framework and no .DSYM file would pass submission without this warning.
> The .dsym file which contains a reference to UIWebView from the grep command is perfectly normal. 
> 
> [We] investigated other leading closed source SDKs to see if their .dsym files contained UIWebView references and they did. The actual artefacts themselves did not contain any reference to UIWebview as is the case with the SmoochSDK.
> 
> We believe this won’t be an issue for integrators going forward.
