### ISSUE TITLE
Memory leak due to SKTSmoochApiClient

### ISSUE THREAD

**Issue by Shyam-Pgmr** [zendesk/sunshine-conversations-ios#208]
**I'm submitting a ...**
  - [x] bug report

 **What is the current behavior?**
Calling Smooch.login() is causing lot of memory leaks internally.

_Memory graph from Xcode:_
<img width="522" alt="Screenshot 2020-04-29 at 9 33 53 PM" src="https://user-images.githubusercontent.com/8200160/80618813-80778a00-8a61-11ea-975b-486c94fd1e84.png">

 **Steps to reproduce**
* Call Smooch.login()

 **What is the expected behavior?**
Ideally there shouldn't be any leaks.

 **Please tell us about your environment:**
- SDK version 7.1.2
- OS version all

**Comment by wmora** [comment]
Thanks for reporting. We've filed the issue internally for the team to review

**Comment by DataWearsAHood** [comment]
Hello Isaak,

Thanks for the update! 
I've passed along your feedback to the dev team (internal ref: SCBE-1157).
