### ISSUE TITLE
IOS SDK login hangs

### ISSUE THREAD

**Issue by billnbell** [zendesk/sunshine-conversations-ios#213]
Using 7.1.2 login works perfectly. But when using 8.0.2/9.0.0/10.0.0 when I call login it just hangs.

```
    SKTSettings *customSettings = [SKTSettings settingsWithIntegrationId:@"STAGE_SMOOCH_INTEGRATION_ID_IOS"];
    customSettings.enableAppDelegateSwizzling = false;
    customSettings.enableUserNotificationCenterDelegateOverride = false;
    [Smooch initWithSettings:customSettings completionHandler:^(NSError * _Nullable error, NSDictionary * _Nullable userInfo) {
       NSLog(@"Smooch initWithSettings for stage");
     }];

then later...

   dispatch_async(dispatch_get_main_queue(), ^{
      [Smooch login:externalId jwt:jwt completionHandler:^(NSError * _Nullable error, NSDictionary * _Nullable userInfo) {
          NSLog(@"Login completion");
       }];
   });
```

I get "Smooch initWithSettings for stage" but the "Login completion" never comes back and is not printed.

I have a valid jwt token and a valid externalId. If I don't make this call I can send messages and [Smooch show] etc. I tried logging off, and then logging in, and it did not help. I generally just keep getting the "Login completion" not printing.

It would be great to make sure you always return something in the login completionHandler even if there is an error.

The Android externalId works perfectly even on the current latest versions.

Staging info -

externalId: 6f9fb5d0-fd15-4a52-94a5-98b74c703525
jwt: is valid.
{
  "alg": "HS256",
  "typ": "JWT",
  "kid": "app_removed"
}

![image](https://user-images.githubusercontent.com/25377089/108028818-a880ab80-6fe9-11eb-872d-d4714d49b9e6.png)

**Comment by billnbell** [comment]
Bump

**Comment by billnbell** [comment]
Any thoughts on this? Is there some other logic I can add to get the results back from Login ? Do a retry?

**Comment by IAmConorNolan** [comment]
Hey @billnbell, thank you for reaching out!

I've been investigating this issue further and have had some trouble reproducing using the init/login code provided above. Would it be possible to get a sample Xcode project in which this is occurring? :)

**Comment by billnbell** [comment]
The project is pretty large - and not sure what you need....

**Comment by DataWearsAHood** [comment]
@billnbell 
You may want to start from the /DemoApp included in the repo and add your modifications individually until the issue is reliably/easily reproducible.

**Comment by billnbell** [comment]
I wonder if it might have to do with security TLS 1.2 settings in IOS? Can you send me an Info.plist that works?

I will try to duplicate it too.

**Comment by billnbell** [comment]
OK. I got it to work by not using a completion handler ... i.e. using [Smooch login:externalId jwt:jwt completionHandler:nil];

```
    dispatch_async(dispatch_get_main_queue(), ^{
        [Smooch login:externalId jwt:jwt completionHandler:nil];
          NSLog(@"Logged In !!");
// I was waiting here for it to complete.
        });
```

**Comment by IAmConorNolan** [comment]
Glad to hear you were able to get sorted @billnbell! Thanks for letting us know :)
