### ISSUE TITLE
Keyboard hiding textfield in modal

### ISSUE THREAD

**Issue by ataourirt** [zendesk/sunshine-conversations-ios#215]
**I'm submitting a ...**
  - bug report

 **What is the current behavior?**

Like this previous [issue](https://github.com/zendesk/sunshine-conversations-ios/issues/205), tthe keyboard is on top of the input textfield and hides the user from seeing what he's typing when we show the Smooch conversation in modal.

 **Please tell us about your environment:**
- SDK version: 10.1.0
- OS version: 14.4.2

![IMG_1074](https://user-images.githubusercontent.com/16756293/113170644-0d652d80-9247-11eb-8d11-a47e297721a0.PNG)

**Comment by djustix** [comment]
<img width="409" alt="Screenshot 2021-04-29 at 12 26 09" src="https://user-images.githubusercontent.com/26569678/116537228-421be180-a8e6-11eb-80d8-39eccbf0b4ee.png">

We're having the same issues with 10.1.0 on multiple devices/configs.

**Comment by ataourirt** [comment]
hi @DataWearsAHood, 
In the DemoApp, ` [Smooch show]` is called but on my project, we used `Smooch.newConversationViewController(withId:, completionHandler:)`.
So we don't have the same behavior!

**Comment by DataWearsAHood** [comment]
Hi @ataourirt 

Thanks for the bug report - I've filed it with the dev team.
Keep an eye on release notes to know once it's been addressed. (internal ref: MFD-4039).
