### ISSUE TITLE
Open from Quit mode does not fire didReceiveNotificationResponse

### ISSUE THREAD

**Issue by billnbell** [zendesk/sunshine-conversations-ios#217]
IOS XR, release to PRODUCTION.

The Push Notification on QUIT, user clicks the notification, and it opens the app. But didReceiveNotificationResponse not being called in Release 10.1.

If there an easier way to get the Push Notification in AppDelegate?

**Comment by billnbell** [comment]
customSettings.enableAppDelegateSwizzling = false;
    customSettings.enableUserNotificationCenterDelegateOverride = false;
    [Smooch initWithSettings:customSettings completionHandler:^(NSError * _Nullable error, ...

**Comment by DataWearsAHood** [comment]
Hi @billnbell,

When disabling swizzling, please be sure to follow all suggestions provided here: https://docs.smooch.io/api/ios/Classes/SKTSettings.html#//api/name/enableAppDelegateSwizzling

https://docs.smooch.io/guide/native-ios-sdk/#step-4-test-it-out

**Comment by DataWearsAHood** [comment]
Hi @billnbell,
The Dev team has added this item to their backlog. Thank you for the feedback suggestion.
