### ISSUE TITLE
iPad "+" button: UIAlertControllerStyleActionSheet crash

### ISSUE THREAD

**Issue by andyzaharia** [zendesk/sunshine-conversations-ios#221]
**I'm submitting a ...**

- [ √] bug report

**Current Behaviour**

App crashes when you press the plus button because Smooch is trying to present an action sheet which is not supported on iPad OS.

**Expected Behavior**
No crash.

**Steps to Reproduce**
Open any app that implements smooch on iPad and press the + button.

**Environment**

- SDK version: 10.1.0
- OS version: iOS 12.4 & 14.5
- Device type: iPad
- Integration type: Cocoapods

<img width="1042" alt="CleanShot 2021-07-15 at 14 33 30@2x" src="https://user-images.githubusercontent.com/649034/125781465-ec4ee1fc-e7de-4636-87af-06522f7e9621.png">

**Comment by DataWearsAHood** [comment]
Hi @andyzaharia ,

Thanks for flagging this one - it's already on the dev team's radar for an upcoming release!
Keep an eye on release notes to know once it's been fixed.

**Comment by andyzaharia** [comment]
So... is no one really bothered by this crash or whats happening with this SDK? Should we just nuke it out of our app entirely?

Seems like some really lousy support you guys have here unfortunately.

**Comment by DataWearsAHood** [comment]
FYI - this should be fixed with our next release (>v10.1.1)
