### ISSUE TITLE
Close bar button and app name do not have the right tint color

### ISSUE THREAD

**Issue by benv33** [zendesk/sunshine-conversations-ios#224]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [x] bug report

**Current Behaviour**
What is the current behavior?
Close bar button and and app name are almost not visible becsaue they have a dark tint color
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-11-11 at 10 43 11](https://user-images.githubusercontent.com/36708096/141326906-db06b5de-3057-440d-9804-61a12dbd0870.png)

**Expected Behavior**
What is the expected behavior?
Close bar button and app name should have a light tint color

**Steps to Reproduce**
Please include steps to reproduce the issue, if possible. If you're unable to reproduce the issue, let us know where you encountered the issue. If the issue is difficult to reproduce, try to outline vague reproduction steps as best you can. Often, a video showing the issue can help us too.
Set you navigation background to a dark color
`UINavigationBarAppearance *navBarAppearance = [[UINavigationBarAppearance alloc] init];
navBarAppearance.backgroundColor = [UIColor blackcolor];`
Set Smooch status bar style to light content style
`settings.conversationStatusBarStyle = UIStatusBarStyleLightContent`
Show smooch conversation:
`[Smooch show];`

**Sample Project or Code Snippet**
Please provide a runnable Sample Project that contains code to reproduce the issue you're experiencing. If this isn't possible, please instead include a code snippet of your initialization code, as well as the code required to reproduce the issue as text. (Please do not send screenshots of code).

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.
Xcode 13.1, iOS 15, objective-c project, cocoapods, latest Smooch SDK

  **Additional Information**
  Please feel free to add any additional context, symbolicated stack traces, related issues, or suggestions here.
Tint color used for the button is SKTNavBarItemText

**Comment by KillianSmith0** [comment]
Hi @benv33 

Out of interest, does setting the barStyle to `UIStatusBarStyleDarkContent` potentially resolve the issue?
Have you tried the newer NavigationBarAppearance APIs to customize the styling further?
Can you try something like the following to see if it resolves the issue?

```objc
if (@available(iOS 13.0, *)) {
    UINavigationBarAppearance *appearance = [[UINavigationBarAppearance alloc] init];
    [appearance configureWithOpaqueBackground];
    [appearance setBackgroundColor:[UIColor blueColor]];
    [appearance setTitleTextAttributes:@{ NSForegroundColorAttributeName: [UIColor whiteColor] }];
    UIBarButtonItemAppearance *buttonAppearance = [[UIBarButtonItemAppearance alloc] init];
    [buttonAppearance.normal setTitleTextAttributes:@{ NSForegroundColorAttributeName: [UIColor whiteColor] }];
    UIBarButtonItemAppearance *doneButtonAppearance = [[UIBarButtonItemAppearance alloc] init];
    [buttonAppearance.normal setTitleTextAttributes:@{ NSForegroundColorAttributeName: [UIColor whiteColor] }];
    appearance.buttonAppearance = buttonAppearance;
    appearance.doneButtonAppearance = doneButtonAppearance;
    appearance.backButtonAppearance = doneButtonAppearance;
    UINavigationBar.appearance.standardAppearance = appearance;
    UINavigationBar.appearance.scrollEdgeAppearance = appearance;
    UINavigationBar.appearance.compactAppearance = appearance;
    if (@available(iOS 15.0, *)) { // For compatibility with earlier iOS.
        UINavigationBar.appearance.compactScrollEdgeAppearance = appearance;
    }
}
```

```swift
if #available(iOS 13.0, *) {
    let appearance = UINavigationBarAppearance()
    appearance.configureWithOpaqueBackground()
    appearance.backgroundColor = .blue
    appearance.titleTextAttributes = [.foregroundColor: UIColor.white]
    let buttonAppearance = UIBarButtonItemAppearance()
    buttonAppearance.normal.titleTextAttributes = [.foregroundColor: UIColor.white]
    let doneButtonAppearance = UIBarButtonItemAppearance()
    doneButtonAppearance.normal.titleTextAttributes = [.foregroundColor: UIColor.white]
    appearance.buttonAppearance = buttonAppearance
    appearance.doneButtonAppearance = doneButtonAppearance
    appearance.backButtonAppearance = doneButtonAppearance
    UINavigationBar.appearance().standardAppearance = appearance
    UINavigationBar.appearance().scrollEdgeAppearance = appearance
    UINavigationBar.appearance().compactAppearance = appearance
    if #available(iOS 15.0, *) { // For compatibility with earlier iOS.
        UINavigationBar.appearance().compactScrollEdgeAppearance = appearance
    }
}
```


Hope some of this helps

**Comment by benv33** [comment]
Hi @KillianSmith0 ,
This has no effect and I think it's because the sdk sets the button's colour to SKTNavBarItemText so it cannot be overwritten by setting the appearance

Thanks,
Benoit

**Comment by KillianSmith0** [comment]
Are you sure? Can you try this reduced snippet? I was successfully able to change the title (Travel Book for you) to green title using this

```objc
if (@available(iOS 13.0, *)) {
    UINavigationBarAppearance *appearance = [[UINavigationBarAppearance alloc] init];
    [appearance configureWithOpaqueBackground];
    [appearance setBackgroundColor:[UIColor systemRedColor]];
    [appearance setTitleTextAttributes: @{NSForegroundColorAttributeName: [UIColor systemGreenColor]}];

    UIBarButtonItemAppearance *buttonAppearance = [[UIBarButtonItemAppearance alloc] init];
    [buttonAppearance.normal setTitleTextAttributes: @{NSForegroundColorAttributeName: [UIColor systemGreenColor]}];
    appearance.buttonAppearance = buttonAppearance;

    UINavigationBar.appearance.standardAppearance = appearance;
    UINavigationBar.appearance.scrollEdgeAppearance = appearance;
    UINavigationBar.appearance.compactAppearance = appearance;
    if (@available(iOS 15.0, *)) { // For compatibility with earlier iOS.
        UINavigationBar.appearance.compactScrollEdgeAppearance = appearance;
    }
}
```

**Comment by IAmConorNolan** [comment]
Hey @benv33, the latest version has just been released. Hopefully, this will allow you to leverage the above code. :)

**Comment by KillianSmith0** [comment]
One thing to note is that we use largeNavigationTitle for the ConversationList screen. 
Seems like [textAttributes are ignored](https://developer.apple.com/forums/thread/79117) when using this format.

**Comment by benv33** [comment]
Hi @IAmConorNolan, it worked for the title but did not for the button, I still see SKTNavBarItemText as the tintColor.
![Simulator Screen Shot - iPhone 13 Pro Max - 2021-12-15 at 10 21 10](https://user-images.githubusercontent.com/36708096/146214123-e3752de2-5dde-441f-a0e3-86fae8189c36.png)

**Comment by alarkirikal** [comment]
@IAmConorNolan Hi, we are also facing with the issue of not being able to customise the X, which kind of blocks one from using a range of colors for the navigation bar. Is there any progress on this, as it's been months?

**Comment by DataWearsAHood** [comment]
> Unfortunately the button is provided by the system and cannot be customised - the appearance of the button changes depending on light or dark mode

> A workaround could be for the integrator to set the Navbar to dark mode. It could look something like the following:
```
// Objective-c:
UINavigationBar.appearance.overrideUserInterfaceStyle = UIUserInterfaceStyleDark;

// Swift:
UINavigationBar.appearance().overrideUserInterfaceStyle = .dark
```
