### ISSUE TITLE
End of support iOS 8.0

### ISSUE THREAD

**Issue by d-date** [zendesk/sunshine-conversations-ios#226]
The latest Xcode warns 'The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99.'

**I'm submitting a ...**

- [x] bug report

**Current Behaviour**
What is the current behavior?

Target Integrity warning on Xcode.

**Expected Behavior**

End of support of iOS 8.0.
See iOS and iPadOS usage: https://developer.apple.com/support/app-store/

**Steps to Reproduce**

Install Smooch via Swift PM.

**Sample Project or Code Snippet**

**Environment**

- SDK version: 10.1.1
- OS version: Xcode 13.2.1
- Device type
- Integration type (Cocoapods, Carthage, Manual): Swift PM (Maybe occur in all integration types)

**Comment by DataWearsAHood** [comment]
Hi @d-date,

Looks like this has been addressed in 10.1.2: https://github.com/zendesk/sunshine-conversations-ios/blob/master/SampleApp/Sunshine%20Conversations%20Sample%20App.xcodeproj/project.pbxproj
