### ISSUE TITLE
Sunshine issue with RTL

### ISSUE THREAD

**Issue by mEldewaik** [zendesk/sunshine-conversations-ios#227]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [x] bug report

**Current Behaviour**
What is the current behavior?
i can't find the back button it is under the logo so the user will not be able to see the back button

![Simulator Screen Shot - iPhone 13 Pro - 2022-06-13 at 19 02 45](https://user-images.githubusercontent.com/29314628/173406870-bba8b3b8-ecf9-4876-9012-f2e11b7b4d66.png)

**Expected Behavior**
What is the expected behavior?
When the app is RTL the logo and project name become in the right place

**Steps to Reproduce**
Please include steps to reproduce the issue, if possible. If you're unable to reproduce the issue, let us know where you encountered the issue. If the issue is difficult to reproduce, try to outline vague reproduction steps as best you can. Often, a video showing the issue can help us too.

When supporting Any RTL language like Arabic you can see the issue 
the app is working fine when the LTR direction 

**Sample Project or Code Snippet**
Please provide a runnable Sample Project that contains code to reproduce the issue you're experiencing. If this isn't possible, please instead include a code snippet of your initialization code, as well as the code required to reproduce the issue as text. (Please do not send screenshots of code).

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

- SDK version: 10.1.3
- OS version: iOS 15.2
- Device type: iphone 13
- Integration type (Cocoapods, Carthage, Manual): cocoapods

  **Additional Information**
  Please feel free to add any additional context, symbolicated stack traces, related issues, or suggestions here.

**Comment by mEldewaik** [comment]
any support here plz

**Comment by DataWearsAHood** [comment]
@mEldewaik can you confirm if this issue remains with the [latest release](https://github.com/zendesk/sunshine-conversations-ios/releases/tag/12.0.0)?
