### ISSUE TITLE
Failing to create second conversation

### ISSUE THREAD

**Issue by alarkirikal** [zendesk/sunshine-conversations-ios#228]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [X] bug report
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current Behaviour**
With one existing conversation, I am unable to start a second one.

Calling the `createConversation` API method will result in a `400 bad request` error.
Tapping `New conversation` in the bottom of conversation list screen will result in a `<SMOOCH::ERROR> failed to create conversation` 

**Expected Behavior**
I expect to be able to start a new conversation as a separate ticket.

**Steps to Reproduce**
1. Integrate Smooch SDK.
2. Start a conversation
3. Close it
4. Try to start next one

**Sample Project or Code Snippet**
I am currently using this API call in Swift to initiate the conversation. Worked nicely with the first conversation, does not with the second one.

```
Smooch.createConversation(
    withName: "Support request",
    description: nil,
    iconUrl: nil,
    avatarUrl: nil,
    metadata: [:],
    message: nil,
    completionHandler: smoochCompletionHandler
)
```

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

SDK version: 10.1.3
OS Version: iOS 15.4
Device Type: Simulator
Integration Type: Cocoapods

  **Additional Information**
  Please feel free to add any additional context, symbolicated stack traces, related issues, or suggestions here.

**Comment by tomferreira** [comment]
Did you enable multiconversation on server side?

See the `multiConvoEnabled` setting at https://docs.smooch.io/rest/#operation/updateApp

**Comment by DataWearsAHood** [comment]
@alarkirikal can you confirm if the previous suggestion helped?
If not, does this issue remain with the [latest release](https://github.com/zendesk/sunshine-conversations-ios/releases/tag/12.0.0)?
