### ISSUE TITLE
Can not cancel sending video when it's loading

### ISSUE THREAD

**Issue by thien-axonvibe** [zendesk/sunshine-conversations-ios#229]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [ ] bug report

**Current Behaviour**
What is the current behavior?

https://user-images.githubusercontent.com/76471917/185284829-b8e64433-9207-463a-a00f-1adfc7693b07.mp4

**Expected Behavior**
What is the expected behavior?
Disable cancel button or can tap on cancel button when loading video

**Steps to Reproduce**
Please include steps to reproduce the issue, if possible. If you're unable to reproduce the issue, let us know where you encountered the issue. If the issue is difficult to reproduce, try to outline vague reproduction steps as best you can. Often, a video showing the issue can help us too.
1. Tap on item menu
2. Tap on the Photo & Video Library
3. Choose a video from library
4. Tap on Choose button
5. While loading video, tap on Cancel button -> Nothing happened

**Sample Project or Code Snippet**
Please provide a runnable Sample Project that contains code to reproduce the issue you're experiencing. If this isn't possible, please instead include a code snippet of your initialization code, as well as the code required to reproduce the issue as text. (Please do not send screenshots of code).

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

- SDK version 10.1.3
- OS version 15.6
- Device type iPhone SE
- Integration type (Cocoapods, Carthage, Manual) Manual

  **Additional Information**
  Please feel free to add any additional context, symbolicated stack traces, related issues, or suggestions here.

**Comment by DataWearsAHood** [comment]
@Thientnu97  can you confirm if this issue remains with the [latest release](https://github.com/zendesk/sunshine-conversations-ios/releases/tag/12.0.0)?

**Comment by Thientnu97** [comment]
Yes @DataWearsAHood , this issue remains with the latest

**Comment by michaelodonnell** [comment]
We won't address this limitation as this product is in maintenance mode, and we need to prioritize reliability and stability issues only.
