### ISSUE TITLE
Missing localized strings

### ISSUE THREAD

**Issue by nikolas-theodosis** [zendesk/sunshine-conversations-ios#232]
It seems there are some missing strings in the list provided in the [documentation](https://docs.smooch.io/guide/native-ios-sdk/#adding-more-languages). For example, "My Conversations" and "New conversation" are not there. Although I can override "My Conversations" by adding that key manually I cannot do the same with "New conversation" or it simply doesn't work.

**Comment by gabysillis** [comment]
Hi, Nikolas, I had the same issues. Are you talk about de button who creates a new conversation? if it is, the string for this button is "Create conversation".

**Comment by nikolas-theodosis** [comment]
> Hi, Nikolas, I had the same issues. Are you talk about de button who creates a new conversation? if it is, the string for this button is "Create conversation".

Thanks @gabysillis! Still the documentation needs to be updated though

**Comment by DataWearsAHood** [comment]
Thanks @gabysillis!

@nikolas-theodosis I'll let the doc-team know about the omission 🙏
