### ISSUE TITLE
Smooch`-[SKTRemoteOperationScheduler execute]:  deadlock.

### ISSUE THREAD

**Issue by andyzaharia** [zendesk/sunshine-conversations-ios#233]
Using v11 and v12 seems to cause the same deadlock at the app start in SKTRemoteOperationScheduler. I'm encountering deadlocks caused by -[SKTRemoteOperationScheduler execute] call. From what I can tell right now it only happens in the simulator and it was happening for quite a while but never really bothered to report it. Seeing this still happens with v12 maybe its time to actually report it :)

So, long story short, this call seems to block the mainthread which obviously is not perfect and completely freezes the app.

**I'm submitting a ...**

- [ √] bug report

**Current Behaviour**
- Deadlock.

**Expected Behavior**
- No deadlock.

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

- v12.0.0
- iOS 16.1
- Xcode 14.1
- Simulator
- Integration type: Cocoapods

**Comment by adellibovi** [comment]
This seems to still be happening on the latest version 12.1.0, app gets completely frozen. Is the issue being investigated?

**Comment by michaelodonnell** [comment]
We won't address this limitation as this product is in maintenance mode, and we need to prioritize reliability and stability issues only.

**Comment by andyzaharia** [comment]
@michaelodonnell thank for your reply, but isn't a deadlocking issue a maintenance task/issue? Tho.., I got the message, we need to remove this framework from our app.

**Comment by cassianomonteiro** [comment]
@michaelodonnell If this is in maintenance mode, will there be a replacement? It's not great to hear that this is no longer maintained since it's being used in production of our own app.
