### ISSUE TITLE
The smooch navigation replace the override navigation on the first sending message.

### ISSUE THREAD

**Issue by thien-axonvibe** [zendesk/sunshine-conversations-ios#234]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [ ] bug report

**Current Behaviour**
On the first sending message, smooch chat automatically  override the custom navigation by the smooch's navigation even I overrode it before.

**Expected Behavior**
Do not override to the smooch's one when I override it before

**Steps to Reproduce**
1. Init smooch 
2. send a message

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

- SDK version
- OS version
- Device type
- Integration type (Cocoapods, Carthage, Manual)

  **Additional Information**

https://user-images.githubusercontent.com/76471917/229095884-9329ab43-8040-42cd-af7b-2732b64fd6b0.MP4

  Vid:

**Comment by michaelodonnell** [comment]
We won't address this limitation as this product is in maintenance mode, and we need to prioritize reliability and stability issues only.
