### ISSUE TITLE
Carthage JSON map file doesn't exists

### ISSUE THREAD

**Issue by lucasmarcal-faire** [zendesk/sunshine-conversations-ios#236]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

- [x] bug report
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current Behaviour**
The carthage binary JSON map file doesn't exists, it was removed on this [commit](https://github.com/zendesk/sunshine-conversations-ios/commit/e79908e9b59da2d0a2ef666685e31fd7b1e1ea3d#diff-0f7f7bbece72e014c465ab6a88f44d5dabf5649b68a6aa3b8cf557f45b60ec07)

**Expected Behavior**
What is the expected behavior?

You should see a json at https://raw.githubusercontent.com/smooch/smooch-ios/master/Smooch.json

**Steps to Reproduce**
Please include steps to reproduce the issue, if possible. If you're unable to reproduce the issue, let us know where you encountered the issue. If the issue is difficult to reproduce, try to outline vague reproduction steps as best you can. Often, a video showing the issue can help us too.

- Try to download Smooch with Carthage

**Comment by lucasmarcal-faire** [comment]
cc @gaborvass-zendesk

**Comment by renaudjennymonese** [comment]
We have exactly the same issue, could you please give some update about its resolution? Thanks.

**Comment by gaborvass-zendesk** [comment]
Hi,
Sorry for the issues, I put back the `Smooch.json` file.
Since the framework is delivered as xcframework, your Cartfile should contain only the following line:
`github "zendesk/sunshine-conversations-ios" ~> 12.1.1`

**Comment by lucasmarcal-faire** [comment]
Thank you! 🚀
