### ISSUE TITLE
Retain cycle in SKTConversationViewController

### ISSUE THREAD

**Issue by dmitrii-volkov** [zendesk/sunshine-conversations-ios#237]
**I'm submitting a ...**

- [x] bug report

**Current Behaviour**
Retain cycle in `SKTConversationViewController`.
Instances of `SKTConversationViewController` remain in memory after controller was dismissed.

**Expected Behavior**
`SKTConversationViewController` instances clean up all the resources and free up memory.

**Steps to Reproduce**
1. Setup Smooch SDK so you can create a conversation view controller.
2. Create an instance of a conversation view controller via `Smooch.newConversationViewController()` and then present it, e.g. by calling `UIViewController.present(_:animated:completion)` method.
3. Dismiss conversation view controller by tapping close button in the upper right corner or by calling `UIViewController.dismiss(animated:completion:)` method.
4. Open memory graph by tapping `Debug memory graph` icon in Xcode and search for `SKTConversationViewController`.
5. `SKTConversationViewController` will still be presented in memory.

![image](https://github.com/zendesk/sunshine-conversations-ios/assets/116079453/9ef99686-cd3d-4e86-b85c-92fc8ff2bde9)

**Environment**

- SDK version: 12.1.1
- OS version: 16.4
- Device type: iOS Simulator
- Integration type: SPM

  **Additional Information**
Issue seems to be related to a retain cycle in `SKTConversationViewController` or `SKTOMessagingViewController` classes.
In `viewDidLoad` `NotificationCenter.addObserver(forName:object:queue:using:)` method is called to setup an observation for notification named `SKTInputDisplayedDidChangeNotification`.
Looks like `NotificationCenter.addObserver(forName:object:queue:using:)` last parameter, which is a closure, strongly captures `self` here, which in place holds a strong reference to an object returned from `NotificationCenter.addObserver(forName:object:queue:using:)`. This causes a retain cycle and keeps `SKTConversationViewController` instances in memory.
By printing description of `NSNotificationCenter.default` in debugger, searching for `SKTInputDisplayedDidChangeNotification` and then calling `NSNotificationCenter.default.removeObserver(_:)` with  an address of `__NSObserver` object, the retain cycle is broken and `SKTConversationViewController` is no longer visible in memory debugger.

**Comment by michaelodonnell** [comment]
We won't address this limitation as this product is in maintenance mode, and we need to prioritize reliability and stability issues only.
