### ISSUE TITLE
SKTNavigationBar RTL bug

### ISSUE THREAD

**Issue by VAmpersand** [zendesk/sunshine-conversations-ios#238]
Hello! 
**I'm submitting a bug report**

**Current Behaviour**
SKTNavigationBar and SKTConversationNavigationItemTitleVIew does not support RTL

**Expected Behavior**
SKTNavigationBar and SKTConversationNavigationItemTitleVIew should support RTL

**Steps to Reproduce**
Switch the locale to Persian or Arabic and open a conversation.

**Environment**
- SDK version - 12.1.0
- OS version - iOS 16.4
- Device type - iPhone 14 Pro
- Integration type - Cocoapods
<img width="302" alt="Снимок экрана 2023-08-11 в 09 42 33" src="https://github.com/zendesk/sunshine-conversations-ios/assets/49166976/feb663ae-d6e3-46a5-83a9-777569cc6016">

**Comment by michaelodonnell** [comment]
Fixed.
