### ISSUE TITLE
Ability to see users and conversations on the supportkit.io website

### ISSUE THREAD

**Issue by ghost** [zendesk/sunshine-conversations-ios#24]
I'd really like to be able to see a list of all the users including their properties set through the app, so I have an overview of who my users are. 
Also, I'd like to see the conversations with these users on the website, in case I miss an email from a user.

**Comment by DataWearsAHood** [comment]
Hello!

Thanks for your feedback! This request is already on the product team's radar!
We'll be closing this issue since this is not an issue/bug related to the iOS SDK.
