### ISSUE TITLE
Non-localised strings in Conversations List and Conversation screens

### ISSUE THREAD

**Issue by swissborg-mobile** [zendesk/sunshine-conversations-ios#241]
**I'm submitting a ...**

- [X] bug report

**Current Behaviour**
Some texts from **Conversations List** and **Conversation** screens are not localised in French and German. Please check the following screenshots, the non-localised texts are underlined with red.

In **Conversations List** screen:
<img width="565" alt="Screenshot 2023-10-30 at 12 39 44" src="https://github.com/zendesk/sunshine-conversations-ios/assets/54095832/5e041854-a554-4864-91f6-9ea26ea76e23">

In **Conversation** screen:

<img width="565" alt="Screenshot 2023-10-30 at 12 39 26" src="https://github.com/zendesk/sunshine-conversations-ios/assets/54095832/2fb368d8-630f-4c66-912f-c4fa09a6a2e2">

<img width="565" alt="Screenshot 2023-10-30 at 13 01 11" src="https://github.com/zendesk/sunshine-conversations-ios/assets/54095832/6d7f8cdf-1ba3-4ded-b024-ed847421a82a">

**Expected Behavior**
All these texts should be localised in French and German (and in the other supported languages).

**Steps to Reproduce**
Change the phone (or app) language to French or German.

- SDK version: 12.2.0
- OS version: iOS 17.0
- Device type: iPhone 15
- Integration type (Cocoapods, Carthage, Manual): SPM

**Comment by michaelodonnell** [comment]
These strings can be added to the SDK, but the developer is required to do this.
