### ISSUE TITLE
Smooch init fails with SKTErrorDomainIdentifier error 400

### ISSUE THREAD

**Issue by rakefetWorkiz** [zendesk/sunshine-conversations-ios#244]
**I'm submitting a ...**

- [x]  bug report
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current Behaviour**
When calling `Smooch.initWith(settings)` we get a very frequent error log saying 
`The operation couldn’t be completed. (SKTErrorDomainIdentifier error 400.)`

We cannot reproduce this when running on debug mode, but it happens too frequently to our users, and the error isn't clear enough for us to handle 

**Expected Behavior**
Running `Smooch.initWith(settings)` will successfully init smooch's library, and in case of an error with init, a clear error will be returned so we can know if the issue is with the user's internet connection? with our code? with something else?

**Steps to Reproduce**
We couldn't reproduce this scenario, it just appears too many times on our error logs (Sentry) 

**Sample Project or Code Snippet**
```swift
let appId = ***
let settings = SKTSettings(integrationId: appId)
settings.conversationAccentColor = UIColor(.appAccent)
settings.conversationAccentColorDarkMode = UIColor(.appAccent)
Smooch.forgetLastKnownUser(forAppId: appId)
Smooch.setConversationListDelegate(self)

Smooch.initWith(settings) { (error: Error?, userInfo: [AnyHashable : Any]?) in
    if let error = error {
        if let smoochError = KnownSmoochErrors(rawValue: error.code) {
            Log.warning("Smooch Helper init failed \(error)", feature: .User)
            if smoochError == .unauthorized {
                // Fallback for stored credentials being invalid
                self.onInitUnauthorized()
            }
        } else {
            // ============
            Log.error("Smooch Helper init failed", error: error, feature: .User) // <---- This is where the issue is sent to sentry
            // ============
        }
        self.initFailed = true
    } else {
        Log.warning("Init Smooch Helper done", feature: .User)
        self.isInitialized = true
        if self.pendingIdentity {
            self.identify()
        }
    }
}
```

**Environment**
Production

- SDK version - ~> 12.2.0
- OS version -> iOS 17.2.1, iOS 17.1.2, iOS 16.6.1 and more..
- Device type -> iPhone 14 Pro Max, iPhone 13 Pro Max, iPhone 13 and more..
- Integration type  -> Cocoapods

  **Additional Information**

Stack trace: 
```
  ***              0x1013974c0  SentryHelper.capture (SentryHelper.swift:64)
  ***              0x100ef9b68  SentryHelper.capture (Logger.swift)
  ***              0x100ef9b68  Log.error (Logger.swift:52)
  ***              0x100d3d1b4  Log.error (<compiler-generated>)
  ***              0x100d3d1b4  SmoochHelper.setup (SmoochHelper.swift:67)
  ***              0x100d3d28c  thunk for closure (<compiler-generated>)
  Smooch              0x103421514  +[Smooch failWithError:level:completionHandler:] (Smooch.m:224)
  Smooch              0x103421f98  +[Smooch initWithSettings:completionHandler:] (Smooch.m)
  ***              0x100d3cec8  SmoochHelper.setup (SmoochHelper.swift:62)
  ***              0x100cea1d4  UserSettings.setUserSettings (UserSettings.swift:534)
  libswift_Concurrency0x1b830dac0  swift::runJobInEstablishedExecutorContext
  libswift_Concurrency0x1b830ed50  swift_job_runImpl
  libdispatch         0x1b50338a4  _dispatch_main_queue_drain
  libdispatch         0x1b50335ac  _dispatch_main_queue_callback_4CF
  CoreFoundation      0x1ad065018  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
  CoreFoundation      0x1ad061d24  __CFRunLoopRun
  CoreFoundation      0x1ad061474  CFRunLoopRunSpecific
  GraphicsServices    0x1f05e24f4  GSEventRunModal
  UIKitCore           0x1af485628  -[UIApplication _run]
  UIKitCore           0x1af484c64  UIApplicationMain
  SwiftUI             0x1b1e954b4  OUTLINED_FUNCTION_31
  SwiftUI             0x1b1e952f8  OUTLINED_FUNCTION_31
  SwiftUI             0x1b1b05e8c  OUTLINED_FUNCTION_26
```

**Comment by rakefetWorkiz** [comment]
Any insights here?

**Comment by swissborg-mobile** [comment]
We have the same issue. Any update?

**Comment by michaelodonnell** [comment]
@rakefetWorkiz - Do you mind submitting this issue on a Zendesk Support ticket please, and we will investigate. Please include as much info as possible as documented [here](https://developer.zendesk.com/documentation/classic-web-widget-sdks/getting_started/ticket-submission-guidelines-for-mobile-sdk-developers/).

**Comment by IanArb** [comment]
Please submit bug reports to [Zendesk](https://support.zendesk.com/hc/en-us/articles/4408843597850) and be sure to consult our [Getting help section](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/getting_support_on_zendesk_mobile_sdks/) of our documentation.
