### ISSUE TITLE
Xcode warnings

### ISSUE THREAD

**Issue by via-guy** [zendesk/sunshine-conversations-ios#246]
**I'm submitting a ...**

- [x] bug report

**Current Behaviour**
Compilation warnings are thrown for documentation:

***SKTConversation.h***
In protocol `SKTConversationDelegate` for function `conversationListDidRefresh:` the `@param` value uses the type and not the name.

***Smooch.h***
The functions `startConversationWithCompletionHandler:` and `handleUserNotificationActionWithIdentifier:` contain the error:

> Declaration is marked with '`@deprecated`' command but does not have a deprecation attribute

You need to add something like `__attribute__((deprecated("use <some other function> instead")));` to the function definitions.

**Expected Behavior**
No warnings should be thrown.

**Steps to Reproduce**
Add the `Smooch` library as a dependency to an app through Swift Package Manager in Xcode 15 and compile.

**Environment**
Please let us know the following details about the environment in which you encountered this issue, as well as any other relevant information.

- SDK version: 12.2.0
- OS version: macOS 14.4.1, building for iOS 17.4
- Device type: iOS
- Integration type: SPM

**Comment by michaelodonnell** [comment]
We can't prioritize work on Xcode warnings on this SDK.
