### ISSUE TITLE
Spam Protection / Ability to block users

### ISSUE THREAD

**Issue by ghost** [zendesk/sunshine-conversations-ios#26]
I was thinking about what would happen if a user writes a lot of messages into the SupportKit conversation and figured that doing so would be quite easy.

So I suggest that you implement a spam protection (Like only 10 messages per minute would be enough) so that can't happen. 

Additionally, you could add the ability to block user tokens or even emails or names to prevent them from writing bad stuff to the supporter. 

I know this is not the most important thing right now though.

**Comment by s5** [comment]
We have an abusive user over at Treat and would love the ability to block them from lighting up our Slack. Something like... /sk !block would do the trick

**Comment by mtaweel** [comment]
Is this implemented already or not yet?

**Comment by jpjoyal** [comment]
We haven't added this as a built-in concept to the platform. Most helpdesk we integrate with support this feature natively. See these help articles for [Zendesk](https://support.zendesk.com/hc/en-us/articles/203690976-Suspending-a-user), [Helpscout](http://docs.helpscout.net/article/307-spam ) & [Front](https://community.frontapp.com/t/y76kfc/product-update-08032016)

A workaround to do it on Smooch directly would be to set the user [email field](http://docs.smooch.io/api/ios/Classes/SKTUser.html#//api/name/email) to something like `spammer@blacklist.com` and check for that email before showing the conversation UI. Setting the email can also be done from your server via the [AppUser Update API](http://docs.smooch.io/rest/#update).

**Comment by DataWearsAHood** [comment]
Hello!

There is now a tool in the Sunshine Conversations platform called `Pipeline API` that allows an external processor to filter and/or decorate incoming messages on the fly.
One such 3rd-party than can help with this is [Tisane](https://app.smooch.io/integrations/tisane).

We'll be closing this one since this is not an issue related to the iOS SDK.
