### ISSUE TITLE
Doesn't handle HTML links.

### ISSUE THREAD

**Issue by williamsjj** [zendesk/sunshine-conversations-ios#31]
If you insert HTML links into your case response like:

![image](https://cloud.githubusercontent.com/assets/119410/5058376/0f4488b0-6ca3-11e4-9f5a-0322aa5ddb17.png)

What the user sees is: 

![image](https://cloud.githubusercontent.com/assets/119410/5058386/691e0334-6ca3-11e4-8b7b-997a939cabea.png)

SupportKit should honor the `<a href="">` tags in responses as links.

**Comment by DataWearsAHood** [comment]
Hello!

I was just testing this with the Agent Workspace and look like any URL (wth surrounding _spaces_) will be turned into a hyperlink.
![image](https://user-images.githubusercontent.com/44448030/97198776-969ea280-1785-11eb-8e23-12acdb56cc28.png)
![image](https://user-images.githubusercontent.com/44448030/97198730-8b4b7700-1785-11eb-9dd6-ca936440de62.png)

For sending rich-link buttons, please check out [shorthand for link-buttons](https://docs.smooch.io/guide/shorthand/) or [sending link-buttons via API](https://docs.smooch.io/guide/structured-messages/#link-buttons)
