### ISSUE TITLE
Option to load chat links in UIWebView

### ISSUE THREAD

**Issue by williamsjj** [zendesk/sunshine-conversations-ios#33]
It would be really helpful if the chat/conversation view would present a modal UIWebView that loaded the page for a tapped link from the chat. Being taken all the way out the app when the user taps a link breaks continuity and is problematic for our users who have Safari disabled.

**Comment by kidbombay** [comment]
Are we in the future yet?

**Comment by nikitaKoniukh** [comment]
Hi! Can we already show the content of the link without leaving the app?

**Comment by nikitaKoniukh** [comment]
> Thanks Jason.
> This is in our backlog and will be part of a future release.
Hi. I have one question... How I can catch the url link from Smooch chat before he transfer me to safari? Is it possible?

**Comment by DataWearsAHood** [comment]
Hello!

This sounds a lot like the functionality offered via [Conversation Extensions (a.k.a. WebViews)](https://docs.smooch.io/guide/conversation-extensions/)
