### ISSUE TITLE
APN HTTP/2 API support?

### ISSUE THREAD

**Issue by russbishop** [zendesk/sunshine-conversations-ios#79]
Is Smooch using the new Apple push notification API?

The reason I ask is that the new API doesn't require separate development and production certificates which simplifies things quite a bit.

**Comment by mspensieri** [comment]
We're not using it yet, but definitely planning to upgrade

**Comment by DataWearsAHood** [comment]
Hi Peter,

Thanks for reporting this; I am happy to report it's in the dev pipeline!
Subscribe to this repo's releases page to know once it's been shipped!
